vaadin/beverage-starter-flow

README.md
add a badge to Readme, 
the channel to link to is `vaadin-flow/Lobby`
issue: https://github.com/vaadin/flow/issues/2566
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/112)
=> Add badge to Readme

documentation/integrating-a-web-component.asciidoc, documentation/polymer-template-based-view.asciidoc, pom.xml, src/main/java/com/vaadin/starter/beveragebuddy/ui/AbstractEditorDialog.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/PaperToast.java, src/main/webapp/frontend/bower.json, src/main/webapp/frontend/index.html
Added back the removed index.html file and fixed it.
Also added a mention to the documentation about existance of this file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/110)
=> Update to 10.0.0.alpha3 and add index.html

pom.xml
update Pom file
related with generated URL
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/113)
=> Fix a Route issue

src/main/java/com/vaadin/starter/beveragebuddy/backend/ReviewService.java
Backend date can be in the future. 
set month max to 9.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/114)
=> Fix a bug on random backend date generater

pom.xml, src/main/java/com/vaadin/starter/beveragebuddy/backend/ReviewService.java, src/main/webapp/frontend/index.html
merge if needed.
add styles.html to index file for productionMode;
update directory of jetty.extra.resource.base.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/115)
=> Add style to index

pom.xml, src/main/java/com/vaadin/starter/beveragebuddy/ui/CategoriesList.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/ReviewsList.java, src/main/webapp/frontend/bower.json, src/main/webapp/frontend/index.html, src/main/webapp/frontend/package.json, src/main/webapp/frontend/styles.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/118)
=> Use newest Flow version.

pom.xml, src/main/java/com/vaadin/starter/beveragebuddy/ui/MainLayout.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/120)
=> Update version to 1.0.0.alpha7

src/main/java/com/vaadin/starter/beveragebuddy/ui/CategoriesList.java
Makes it consistent with the other view in the app
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/119)
=> Use Valo icons in category list view

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/121)
=> Update Flow version.

src/main/java/com/vaadin/starter/beveragebuddy/ui/CategoriesList.java, src/main/webapp/frontend/styles.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/122)
=> Add a button for the edit feature on Categories list

pom.xml, src/main/java/com/vaadin/starter/beveragebuddy/ui/CategoriesList.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/124)
=> Flow alpha10

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/132)
=> Update flow-maven-plugin version, use correct repo for it.

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/133)
=> fix missing version for production mode

pom.xml, src/main/java/com/vaadin/starter/beveragebuddy/ApplicationServiceInitListener.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/AbstractEditorDialog.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/CategoriesList.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/CategoryEditorDialog.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/ConfirmationDialog.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/GeneratedPaperDialog.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/IronAnnounceEvent.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/MainLayout.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/PaperToast.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/ReviewEditorDialog.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/ReviewsList.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/converters/LocalDateToStringConverter.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/converters/LongToStringConverter.java, src/main/resources/log4j.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/137)
=> Update platform version

src/main/java/com/vaadin/starter/beveragebuddy/ui/CategoriesList.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/142)
=> using verticalLayout in categoryList

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/148)
=> Remove unnecessary properties and dependencies from POM

pom.xml
Added coment for why the logger 
dependency exists
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/155)
=> Added comment for logger

pom.xml, src/main/java/com/vaadin/starter/beveragebuddy/ui/views/categorieslist/CategoriesList.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/168)
=> Update to new platform.

src/main/java/com/vaadin/starter/beveragebuddy/ui/views/categorieslist/CategoryEditorDialog.java
Fixes #172
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/174)
=> Don't show a warning when category without reviews is removed

src/main/java/com/vaadin/starter/beveragebuddy/backend/StaticData.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/views/categorieslist/CategoriesList.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/views/reviewslist/ReviewEditorDialog.java
Add validator for category selection;
After remove the category, assign the affected reviews to Undefined
category.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/179)
=> Fix NPE when category is unselected

pom.xml
Includes a critical fix for vaadin-grid
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/183)
=> Use vaadin 10.0.0-beta2

README.md, documentation/polymer-template-based-view.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/184)
=> Replace usage of Vaadin Elements with Vaadin Components

src/main/webapp/frontend/styles/shared-styles.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/185)
=> workaround for fixing navigational items "deadZone"

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/188)
=> Update vaadin version from 10.0.0.beta2 to 10.0.0.beta3

pom.xml, src/main/java/com/vaadin/starter/beveragebuddy/backend/Review.java, src/main/java/com/vaadin/starter/beveragebuddy/backend/ReviewService.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/encoders/LocalDateToStringEncoder.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/encoders/LongToStringEncoder.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/views/reviewslist/ReviewsList.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/191)
=> Update to Flow beta5

pom.xml, src/main/java/com/vaadin/starter/beveragebuddy/ui/MainLayout.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/192)
=> Removed @Theme declaration

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/202)
=> Update platform to beta8

pom.xml
Add a property for the plugin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/206)
=> Update flow-maven-plugin version

src/main/webapp/frontend/styles/shared-styles.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/208)
=> Remove horizontal scrollbar and fix layout problems on IE11

src/main/java/com/vaadin/starter/beveragebuddy/ui/common/AbstractEditorDialog.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/views/categorieslist/CategoryEditorDialog.java
Fixes #207
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/209)
=> Remove an empty category

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/211)
=> Update platform dependency to Beta9

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/213)
=> Update flow version to beta10

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/221)
=> Update platform to RC2

pom.xml
Update jetty server
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/222)
=> Update platform to RC3

src/main/webapp/frontend/src/views/reviewslist/reviews-list.html, src/main/webapp/frontend/styles/shared-styles.html
Closes #229
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/230)
=> Remove horizontal scroll without with changes

src/main/java/com/vaadin/starter/beveragebuddy/ui/views/reviewslist/ReviewsList.java, src/main/webapp/frontend/src/views/reviewslist/reviews-list.html
Fixes #102
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/239)
=> Set "New Review" and "Edit" button text from Java

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/242)
=> Unify starters pom.xml

src/main/java/com/vaadin/starter/beveragebuddy/backend/CategoryService.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/views/categorieslist/CategoriesList.java
Fixes #244
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/247)
=> Provide the undefined category accessor and disable its edit

src/main/java/com/vaadin/starter/beveragebuddy/ui/common/AbstractEditorDialog.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/common/ConfirmationDialog.java
Fixes #248
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/249)
=> Avoid main dialog closing when confirmation dialog is opened

src/main/java/com/vaadin/starter/beveragebuddy/ui/common/AbstractEditorDialog.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/common/ConfirmationDialog.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/250)
=> Avoid main dialog closing when confirmation dialog is opened (#249)

src/main/java/com/vaadin/starter/beveragebuddy/ui/common/AbstractEditorDialog.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/common/ConfirmationDialog.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/views/categorieslist/CategoriesList.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/252)
=> Use theme variants API

src/main/java/com/vaadin/starter/beveragebuddy/ui/common/AbstractEditorDialog.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/common/ConfirmationDialog.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/views/categorieslist/CategoriesList.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/254)
=> Use theme variants API (#252)

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/270)
=> Making jetty plugin configured better for development

README.md, pom.xml
+ branching information update
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/272)
=> Bump vaadin to 13.0-SNAPSHOT

src/main/java/com/vaadin/starter/beveragebuddy/ui/common/AbstractEditorDialog.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/common/ConfirmationDialog.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/views/categorieslist/CategoriesList.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/views/reviewslist/ReviewsList.java
Completes #268 (adds shortcuts).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/276)
=> Application shortcuts

.travis.yml, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/277)
=> Update to flow server and client versions 2.0-SNAPSHOT

.travis.yml, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/278)
=> Pin Vaadin Platform + remove snapshot repos

.gitignore, README.md, package.json, src/main/java/com/vaadin/flow/server/BootstrapHandler.java, src/main/java/com/vaadin/flow/server/DevModeServer.java, src/main/java/com/vaadin/flow/server/VaadinServlet.java, src/main/webapp/frontend/main.js, src/main/webapp/main.js, src/main/webapp/webpack.config.js, webpack.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/281)
=> Move npm and webpack to the project root folder

.gitignore, webpack.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/285)
=> fix path for index.js file

src/main/java/com/vaadin/flow/server/BootstrapHandler.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/287)
=> Fix rebase problem which removed getBodyAttributes.

package.json, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/288)
=> run npm install if not done already when running maven

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/299)
=> Remove closure dependency

package-lock.json, package.json, webpack.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/289)
=> adding babel to support es5 bundle

.gitignore, pom.xml, webpack.config.js
This is needed when https://github.com/vaadin/flow/pull/5205 is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/302)
=> Produce stats file into build folder, and clean it in maven

pom.xml, src/main/webapp/frontend/main.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/304)
=> Write the imports into main.js

pom.xml
Update BeverageBuddy to be 2.0 instead of 1.0
Update Flow to use SNAPSHOT versions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/316)
=> Update version to 2.0-SNAPSHOT

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/315)
=> Update information on NPM mode.

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/322)
=> re-enable jetty hot reload, and made couple of adjustments in watcher

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/329)
=> Adjust the starter after webpack improvements

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/335)
=> adding validate goal

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/336)
=> Use one goal only

.gitignore, README.md, frontend/src/views/reviewslist/reviews-list.js, frontend/styles/shared-styles.js, pom.xml, src/main/java/com/vaadin/starter/beveragebuddy/ui/MainLayout.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/views/reviewslist/ReviewsList.java
Closes https://github.com/vaadin/beverage-starter-flow/issues/332
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/338)
=> Remove bower leftovers

package-lock.json, package.json, src/main/java/com/vaadin/starter/beveragebuddy/ui/MainLayout.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/347)
=> Remove the dark variant

pom.xml
Already done for master in another commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/352)
=> Update jetty for V13

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/350)
=> Remove branch 2.0 from Readme

README.md, pom.xml
Related to vaadin/platform#645
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/357)
=> Simplify production build to -Pproduction

package-lock.json, package.json, pom.xml, webpack.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/361)
=> Update files based on beta2

webpack.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/362)
=> Rename the goal used in webpack.config.js

drivers.xml, pom.xml, src/test/java/com/vaadin/starter/beveragebuddy/AbstractViewTest.java, src/test/java/com/vaadin/starter/beveragebuddy/ReviewsListIT.java
One test for Lumo theme presence, and another comparing the number of review `div`s with the reported number of reviews in the header. Tests now use TestBench features (`$` and `TestBenchElement`) to locate elements in the shadow root.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/363)
=> 5686 integration tests

src/main/resources/simplelogger.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/369)
=> Do not show Atmosphere debug (info) output by default

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/370)
=> Add default goal

drivers.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/375)
=> Update to Chromedriver 75.0.3770.8 (#374)

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/379)
=> Add Java11 profile

frontend/src/views/reviewslist/reviews-list.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/380)
=> Add vaadin-text-field import to review-list.js

package-lock.json
Fixes #383
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/385)
=> Update package-lock with latest platform deps

package-lock.json, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/391)
=> Update package*.json files

README.md, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/395)
=> Polish readme

package-lock.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/400)
=> Update package-lock.json based on 14.0.0.rc6

package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/401)
=> Update package.json based on 14.0.0.rc6

pom.xml
Part of vaadin/flow#5942
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/407)
=> Add migration profile

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/409)
=> Removed maven-war-plugin to avoid duplicate snapshot versions in target

src/main/java/com/vaadin/starter/beveragebuddy/ui/views/categorieslist/CategoriesList.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/views/reviewslist/ReviewsList.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/405)
=> Added use of Notification theme variants

README.md, frontend/index.html, frontend/index.ts, frontend/src/client-categories.ts, frontend/src/main-layout.ts, frontend/styles/main-layout-styles.css, frontend/styles/shared-styles.css, package-lock.json, package.json, pom.xml, src/main/java/com/vaadin/starter/beveragebuddy/ui/MainLayout.java, tsconfig.json
Fixes #415
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/420)
=> CCDM: use client-side routing

frontend/index.ts, frontend/src/main-layout.ts, frontend/theme.ts
- move the theming code into a separate file to make index.ts more focused
- add comments to open issues in the code where changes are expected
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/423)
=> chore: rearrange the code to focus on the client-side routing features

pom.xml
- Update `flow.version` to 3.0.0.alpha1
- Add `vaadin-prereleases` maven repository
Fixes https://github.com/vaadin/flow/issues/6310
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/425)
=> CCDM: update to Flow 3.0.0.alpha1

frontend/index.ts, frontend/src/client-categories.ts, package-lock.json, package.json
Do not merge until router PR https://github.com/vaadin/vaadin-router/pull/370 is merged, and a new version released.
For local testing  the branch for the PR can be used `npm install git://github.com/vaadin/vaadin-router.git#mcm/fix-action-on-no-change`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/424)
=> CCDM: remove router workaround

frontend/index.ts, package-lock.json, package.json, pom.xml, src/main/java/com/vaadin/starter/beveragebuddy/ui/common/AbstractEditorDialog.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/429)
=> CCDM: use `flow.route` API, prevent server navigation on dirty

frontend/src/components/onboarding-component.ts, package-lock.json, package.json, pom.xml
- TS compilation failures
- match the version of `flow-server-production-mode` to the version of `flow-server`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/433)
=> fix production build issues

frontend/index.ts, frontend/src/components/onboarding-component.ts, package-lock.json, package.json, src/test/java/com/vaadin/starter/beveragebuddy/AbstractViewTest.java
- change the structure so that it's easier to explain step by step
- add comments to the code
- include a @vaadin/router + flow.route as an alternative to flow.start 
also skip onboarding in ITs to make them pass
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/434)
=> rewrite the app entry point to make it a better learning example

.gitignore, frontend/index.ts, package-lock.json, package.json, pom.xml, src/main/java/com/vaadin/starter/beveragebuddy/ui/views/categorieslist/CategoriesList.java, src/test/java/com/vaadin/starter/beveragebuddy/CategoriesListIT.java
Connected to https://github.com/vaadin/flow/issues/6580
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/436)
=> CCDM: use serverSideRoutes API, and latest versions

drivers.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/465)
=> Update chrome driver version

README.md
Removing gitter badge from all starters
part of https://github.com/vaadin/90min-dx-tasks/issues/45
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/466)
=> Remove badge from README

package-lock.json, package.json, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/506)
=> Update to Vaadin 14.1.28

src/main/java/com/vaadin/starter/beveragebuddy/ui/AppShell.java, src/main/java/com/vaadin/starter/beveragebuddy/ui/MainLayout.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/519)
=> adds AppShell class instead of PWA and Viewport annotations

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/beverage-starter-flow/540)
=> adds deprecation message to readme
